### ISSUE TITLE
Bug when having multiple profiles

### ISSUE THREAD

**Issue by jbernardoviana** [dbl-works/aws-manager#35]
If we have two profiles, e.g. `default` and `zero44` ordered like this in the `~/.aws/credentials` file, `.first()` will try to fetch the credential from the `default` profile which does not exist.

Instead of a `Vector`, `credentials` should be something like a `HashMap` 

https://github.com/dbl-works/aws-manager/blob/f9ac19e87a19eff8de637d3f3e3a835c9218769c/src-tauri/src/api.rs#L31-L34

**Comment by morozRed** [comment]
https://github.com/dbl-works/aws-manager/commit/e90f11a2f66a1007de49d579746ec89bc29923b9
